### ISSUE TITLE
not compatible with Nativescript CLI 2.5.0

### ISSUE THREAD

**Issue by DavyDeDurpel** [rborn/nativescript-i18n#37]
Updating to the nativescript 2.5.0 CLI breaks this plugin.  The problem is that each modification of a file triggers and endless loop of rebuilds.

I guess the issue is inside the nativescript-i18n/lib/after-prepare.js hook.

This issue has first been logged in https://github.com/NativeScript/nativescript-cli/issues/2482

**Comment by rborn** [comment]
Ouch,that's pretty ugly :(
I'll try to have a look.

**Comment by ghost** [comment]
@rborn On Android and 2.5.0 with @latest i18n, it's simply creating an empty strings.xml in the android platform so it's broken completely -- iOS have not had any issues.

In 0.0.9 interestingly, no issues

**Comment by DavyDeDurpel** [comment]
Indeed I didn't realize that I had it hardcoded to version 0.0.7.  I can't remember why I did this.  I can also confirm that the latest version is first creating empty strings.xml, then the correct ones to replace them again with empty ones breaking the build proces.

@vbresults for me version 0.0.9 suffers from the same issue as 0.0.7.  Any changes to a .ts or .js file triggers and endless build

**Comment by rborn** [comment]
@vbresults @DavyDeDurpel I posted on https://github.com/NativeScript/nativescript-cli/issues/2482 as I think something is weird with the cli :(

**Comment by ghost** [comment]
@rborn There are two issues here, one is where it's creating the empty strings.xml and another where it generates endless rebuilds.  They seem to be one problem, but I don't think so,

Because I only have the first issue with @latest, if I install nativescript-i18n@0.0.9 then I am able to run the plugin without issues (except I have to patch in the changes to package.json from my PR).

That said, I am using emulators, so maybe that's why I am not having the rebuild issue which seems to be related to livesync/watch (which AFAIK iOS emulator doesn't support).

**Comment by rborn** [comment]
@vbresults I'd like to wait for the telerik guys reply first, something changed in 2.5.0 and I don't know what yet :)

**Comment by zweimal** [comment]
I've fixed it. It looks like a Race Condition issue...
Check PR #38 

Errors thrown: 
```
C:\Users\Zweimal\dev\awesome_app\app\App_Resources\Android\values\strings.xml
C:\Users\Zweimal\dev\awesome_app\app\App_Resources\Android\values-es\strings.xml
Preparing project...
C:\Users\Zweimal\dev\awesome_app\app\App_Resources\Android\values\strings.xml has syntax errors.
error
invalid document source
@#[line:0,col:undefined]

C:\Users\Zweimal\dev\awesome_app\app\App_Resources\Android\values-es\strings.xml has syntax errors.
error
invalid document source
@#[line:0,col:undefined]

(node:10752) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:10752) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Project successfully prepared (android)
```
It keeps building although the errors

Later it breaks again with error:
```
:mergeF0F1F2F3F4DebugResources
C:\Users\Zweimal\dev\awesome_app\platforms\android\src\main\res\values\strings.xml:1:1: Error: Premature end of file.
C:\Users\Zweimal\dev\awesome_app\platforms\android\src\main\res\values-es\strings.xml:1:1: Error: Premature end of file.
:mergeF0F1F2F3F4DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeF0F1F2F3F4DebugResources'.
> C:\Users\Zweimal\dev\awesome_app\platforms\android\src\main\res\values\strings.xml:1:1: Error: Premature end of file.
C:\Users\Zweimal\dev\awesome_app\platforms\android\src\main\res\values-es\strings.xml:1:1: Error: Premature end of file.
```

**Comment by zweimal** [comment]
Code review: 
Hook's promise is always resolved, therefore if there's an error it will continue building and that's not right.

Possible (fast and easy) solution: Check, at least, if the income and outcome file are not empty.
Possible (not so fast) solution: Check XML syntax, invalid or unscaped characters

**Comment by rborn** [comment]
Hey everyone, updated and pushed to npm, could you guys play with it and see if it's working properly (I only tested with pure JS, so somebody playing with Angular and/or TypeScript ?)

Thanks a lot for helping with this repo 😸

**Comment by DavyDeDurpel** [comment]
I just did a few tests with Angular and Typescript and all known issues are solved.  So no more empty strings.xml files and no more endless build loops.   :+1: :+1: :+1:

It's not perfect though because the application still gets refreshed twice.  The first time for the file that got changed and the second time due to the strings.xml files between copied.
Most of the time these strings.xml files won't have been changed.

I guess that this second refresh could be avoided if you would only copy the xml files in case something actually changed?  Maybe just comparing the modification dates could do the trick.

> 11:34:16 AM - File change detected. Starting incremental compilation...
11:34:18 AM - Compilation complete. Watching for file changes.
Executing before-prepare hook from c:\ns\passerelle-mobile\hooks\before-prepare\nativescript-dev-android-snapshot.js
Executing before-prepare hook from c:\ns\passerelle-mobile\hooks\before-prepare\nativescript-dev-typescript.js
Executing before-prepare hook from c:\ns\passerelle-mobile\hooks\before-prepare\nativescript-i18n.js
Executing before-prepare hook from c:\ns\passerelle-mobile\hooks\before-prepare\nativescript-push-notifications.js
Preparing project...
Project successfully prepared (Android)
Executing after-prepare hook from c:\ns\passerelle-mobile\hooks\after-prepare\nativescript-dev-android-snapshot.js
**Transferring project files...**
**Successfully transferred listview.component.js.**
Successfully synced application com.passerelle.mobile on device emulator-5554.
Using  c:\ns\passerelle-mobile\platforms\android\build\outputs\apk\mobile-debug.apk
device: emulator-5554 debug port: 40000
NativeScript Debugger started
[NSDebugAdapter] Ready to attach to application on 40000
[NSDebugAdapter] Connection to target application established on 40000
Skipping prepare.
**Transferring project files...**
**Successfully transferred strings.xml.
Successfully transferred strings.xml.
Successfully transferred strings.xml.**
Successfully synced application com.passerelle.mobile on device emulator-5554.
Using  c:\ns\passerelle-mobile\platforms\android\build\outputs\apk\mobile-debug.apk
device: emulator-5554 debug port: 40000
NativeScript Debugger started
[NSDebugAdapter] Ready to attach to application on 40000
[NSDebugAdapter] Connection to target application established on 40000
JS: LoginService.constructor() username: MASTER
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.

**Comment by rborn** [comment]
@DavyDeDurpel thanks a bunch, I'll have a look 😄

**Comment by ghost** [comment]
@rborn Largely working great except for one thing, in 2.5.0, running tns run ios --clean does not sync the source phrases to the native strings, have to do a prepare for that separately first

**Comment by rborn** [comment]
@vbresults it seems to work for me,can you run this in the [demo](https://github.com/rborn/nativescript-i18n/tree/master/demo) folder and verify? Maybe there is a conflict with another plugin?

**Comment by ghost** [comment]
@rborn Sorry for the delay, LGTM

**Comment by rborn** [comment]
@vbresults I'll keep this open due to: https://github.com/NativeScript/nativescript-cli/issues/2557

**Comment by manojdcoder** [comment]
@rborn Any update on this since NativeScript/nativescript-cli/issues/2557 is fixed now...

I'm not sure whether you have a fix in mind like sass or typescript plugins does, where files are updated / synced only when changes are detected. If not, at least can we avoid running the plugin code when live-sync is enabled to get rid out of multiple reloads.

**Comment by rborn** [comment]
@manojdcoder I still try to find some time to fix this :( a PR would be welcomed :)

**Comment by rborn** [comment]
Working to a [fix](https://github.com/rborn/nativescript-i18n/issues/47).
